//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34003.
// 
#pragma warning disable 1591

namespace Four51.APISDK.Four51Order {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrderSoap", Namespace="http://four51.com/services/order")]
    public partial class Order : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CancelOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback ForwardLineItemsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Order() {
            this.Url = global::Four51.APISDK.Properties.Settings.Default.Four51_APISDK_Four51Order_Order;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CancelOrderCompletedEventHandler CancelOrderCompleted;
        
        /// <remarks/>
        public event ForwardLineItemsCompletedEventHandler ForwardLineItemsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/order/CancelOrder", RequestNamespace="http://four51.com/services/order", ResponseNamespace="http://four51.com/services/order", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CancelOrder(string OrderPayloadID, string SharedSecret) {
            this.Invoke("CancelOrder", new object[] {
                        OrderPayloadID,
                        SharedSecret});
        }
        
        /// <remarks/>
        public void CancelOrderAsync(string OrderPayloadID, string SharedSecret) {
            this.CancelOrderAsync(OrderPayloadID, SharedSecret, null);
        }
        
        /// <remarks/>
        public void CancelOrderAsync(string OrderPayloadID, string SharedSecret, object userState) {
            if ((this.CancelOrderOperationCompleted == null)) {
                this.CancelOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelOrderOperationCompleted);
            }
            this.InvokeAsync("CancelOrder", new object[] {
                        OrderPayloadID,
                        SharedSecret}, this.CancelOrderOperationCompleted, userState);
        }
        
        private void OnCancelOrderOperationCompleted(object arg) {
            if ((this.CancelOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/order/ForwardLineItems", RequestNamespace="http://four51.com/services/order", ResponseNamespace="http://four51.com/services/order", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ForwardLineItems(string OriginalOrderPayloadID, string OutGoingOrderID, string FromUserName, string SupplierCompanyDuns, string Comments, int[] LineItemNumbers) {
            object[] results = this.Invoke("ForwardLineItems", new object[] {
                        OriginalOrderPayloadID,
                        OutGoingOrderID,
                        FromUserName,
                        SupplierCompanyDuns,
                        Comments,
                        LineItemNumbers});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ForwardLineItemsAsync(string OriginalOrderPayloadID, string OutGoingOrderID, string FromUserName, string SupplierCompanyDuns, string Comments, int[] LineItemNumbers) {
            this.ForwardLineItemsAsync(OriginalOrderPayloadID, OutGoingOrderID, FromUserName, SupplierCompanyDuns, Comments, LineItemNumbers, null);
        }
        
        /// <remarks/>
        public void ForwardLineItemsAsync(string OriginalOrderPayloadID, string OutGoingOrderID, string FromUserName, string SupplierCompanyDuns, string Comments, int[] LineItemNumbers, object userState) {
            if ((this.ForwardLineItemsOperationCompleted == null)) {
                this.ForwardLineItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnForwardLineItemsOperationCompleted);
            }
            this.InvokeAsync("ForwardLineItems", new object[] {
                        OriginalOrderPayloadID,
                        OutGoingOrderID,
                        FromUserName,
                        SupplierCompanyDuns,
                        Comments,
                        LineItemNumbers}, this.ForwardLineItemsOperationCompleted, userState);
        }
        
        private void OnForwardLineItemsOperationCompleted(object arg) {
            if ((this.ForwardLineItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ForwardLineItemsCompleted(this, new ForwardLineItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CancelOrderCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ForwardLineItemsCompletedEventHandler(object sender, ForwardLineItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForwardLineItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ForwardLineItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591