//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34011.
// 
#pragma warning disable 1591

namespace Four51.APISDK.Four51PurchaseOrder {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PurchaseOrderSoap", Namespace="http://four51.com/services/purchaseorder")]
    public partial class PurchaseOrder : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdatePOLineItemUnitPriceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PurchaseOrder() {
            this.Url = global::Four51.APISDK.Properties.Settings.Default.Four51_APISDK_Four51PurchaseOrder_PurchaseOrder;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdatePOLineItemUnitPriceCompletedEventHandler UpdatePOLineItemUnitPriceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/purchaseorder/UpdatePOLineItemUnitPrice", RequestNamespace="http://four51.com/services/purchaseorder", ResponseNamespace="http://four51.com/services/purchaseorder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] UpdatePOLineItemUnitPrice([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] LineItemUnitPrice[] LineItemUnitPrices, string SharedSecret) {
            object[] results = this.Invoke("UpdatePOLineItemUnitPrice", new object[] {
                        LineItemUnitPrices,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePOLineItemUnitPriceAsync(LineItemUnitPrice[] LineItemUnitPrices, string SharedSecret) {
            this.UpdatePOLineItemUnitPriceAsync(LineItemUnitPrices, SharedSecret, null);
        }
        
        /// <remarks/>
        public void UpdatePOLineItemUnitPriceAsync(LineItemUnitPrice[] LineItemUnitPrices, string SharedSecret, object userState) {
            if ((this.UpdatePOLineItemUnitPriceOperationCompleted == null)) {
                this.UpdatePOLineItemUnitPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePOLineItemUnitPriceOperationCompleted);
            }
            this.InvokeAsync("UpdatePOLineItemUnitPrice", new object[] {
                        LineItemUnitPrices,
                        SharedSecret}, this.UpdatePOLineItemUnitPriceOperationCompleted, userState);
        }
        
        private void OnUpdatePOLineItemUnitPriceOperationCompleted(object arg) {
            if ((this.UpdatePOLineItemUnitPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePOLineItemUnitPriceCompleted(this, new UpdatePOLineItemUnitPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/purchaseorder")]
    public partial class LineItemUnitPrice {
        
        private string payloadIDField;
        
        private System.Nullable<bool> lockLineItemField;
        
        private int lineNumberField;
        
        private System.Nullable<decimal> unitPriceField;
        
        /// <remarks/>
        public string PayloadID {
            get {
                return this.payloadIDField;
            }
            set {
                this.payloadIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> LockLineItem {
            get {
                return this.lockLineItemField;
            }
            set {
                this.lockLineItemField = value;
            }
        }
        
        /// <remarks/>
        public int LineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/purchaseorder")]
    public partial class ErrorReport {
        
        private string interopIDField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string InteropID {
            get {
                return this.interopIDField;
            }
            set {
                this.interopIDField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdatePOLineItemUnitPriceCompletedEventHandler(object sender, UpdatePOLineItemUnitPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePOLineItemUnitPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePOLineItemUnitPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591