//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34011.
// 
#pragma warning disable 1591

namespace Four51.APISDK.Four51User {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserSoap", Namespace="http://four51.com/services/user")]
    public partial class User : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SyncAssociationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback AssignToGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveFromGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback AssignAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback AssignCostCenterOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public User() {
            this.Url = global::Four51.APISDK.Properties.Settings.Default.Core_Four51User_User;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SyncAssociationsCompletedEventHandler SyncAssociationsCompleted;
        
        /// <remarks/>
        public event SaveCompletedEventHandler SaveCompleted;
        
        /// <remarks/>
        public event AssignToGroupCompletedEventHandler AssignToGroupCompleted;
        
        /// <remarks/>
        public event RemoveFromGroupCompletedEventHandler RemoveFromGroupCompleted;
        
        /// <remarks/>
        public event AssignAddressCompletedEventHandler AssignAddressCompleted;
        
        /// <remarks/>
        public event AssignCostCenterCompletedEventHandler AssignCostCenterCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/user/SyncAssociations", RequestNamespace="http://four51.com/services/user", ResponseNamespace="http://four51.com/services/user", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] SyncAssociations([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] UserAssociation[] Associations, string SharedSecret) {
            object[] results = this.Invoke("SyncAssociations", new object[] {
                        Associations,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void SyncAssociationsAsync(UserAssociation[] Associations, string SharedSecret) {
            this.SyncAssociationsAsync(Associations, SharedSecret, null);
        }
        
        /// <remarks/>
        public void SyncAssociationsAsync(UserAssociation[] Associations, string SharedSecret, object userState) {
            if ((this.SyncAssociationsOperationCompleted == null)) {
                this.SyncAssociationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncAssociationsOperationCompleted);
            }
            this.InvokeAsync("SyncAssociations", new object[] {
                        Associations,
                        SharedSecret}, this.SyncAssociationsOperationCompleted, userState);
        }
        
        private void OnSyncAssociationsOperationCompleted(object arg) {
            if ((this.SyncAssociationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncAssociationsCompleted(this, new SyncAssociationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/user/Save", RequestNamespace="http://four51.com/services/user", ResponseNamespace="http://four51.com/services/user", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] Save([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] UserProperties[] Users, string SharedSecret) {
            object[] results = this.Invoke("Save", new object[] {
                        Users,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveAsync(UserProperties[] Users, string SharedSecret) {
            this.SaveAsync(Users, SharedSecret, null);
        }
        
        /// <remarks/>
        public void SaveAsync(UserProperties[] Users, string SharedSecret, object userState) {
            if ((this.SaveOperationCompleted == null)) {
                this.SaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOperationCompleted);
            }
            this.InvokeAsync("Save", new object[] {
                        Users,
                        SharedSecret}, this.SaveOperationCompleted, userState);
        }
        
        private void OnSaveOperationCompleted(object arg) {
            if ((this.SaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCompleted(this, new SaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/user/AssignToGroup", RequestNamespace="http://four51.com/services/user", ResponseNamespace="http://four51.com/services/user", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AssignToGroup(string UserInteropID, string GroupInteropID, string SharedSecret) {
            this.Invoke("AssignToGroup", new object[] {
                        UserInteropID,
                        GroupInteropID,
                        SharedSecret});
        }
        
        /// <remarks/>
        public void AssignToGroupAsync(string UserInteropID, string GroupInteropID, string SharedSecret) {
            this.AssignToGroupAsync(UserInteropID, GroupInteropID, SharedSecret, null);
        }
        
        /// <remarks/>
        public void AssignToGroupAsync(string UserInteropID, string GroupInteropID, string SharedSecret, object userState) {
            if ((this.AssignToGroupOperationCompleted == null)) {
                this.AssignToGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssignToGroupOperationCompleted);
            }
            this.InvokeAsync("AssignToGroup", new object[] {
                        UserInteropID,
                        GroupInteropID,
                        SharedSecret}, this.AssignToGroupOperationCompleted, userState);
        }
        
        private void OnAssignToGroupOperationCompleted(object arg) {
            if ((this.AssignToGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssignToGroupCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/user/RemoveFromGroup", RequestNamespace="http://four51.com/services/user", ResponseNamespace="http://four51.com/services/user", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveFromGroup(string UserInteropID, string GroupInteropID, string SharedSecret) {
            this.Invoke("RemoveFromGroup", new object[] {
                        UserInteropID,
                        GroupInteropID,
                        SharedSecret});
        }
        
        /// <remarks/>
        public void RemoveFromGroupAsync(string UserInteropID, string GroupInteropID, string SharedSecret) {
            this.RemoveFromGroupAsync(UserInteropID, GroupInteropID, SharedSecret, null);
        }
        
        /// <remarks/>
        public void RemoveFromGroupAsync(string UserInteropID, string GroupInteropID, string SharedSecret, object userState) {
            if ((this.RemoveFromGroupOperationCompleted == null)) {
                this.RemoveFromGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveFromGroupOperationCompleted);
            }
            this.InvokeAsync("RemoveFromGroup", new object[] {
                        UserInteropID,
                        GroupInteropID,
                        SharedSecret}, this.RemoveFromGroupOperationCompleted, userState);
        }
        
        private void OnRemoveFromGroupOperationCompleted(object arg) {
            if ((this.RemoveFromGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveFromGroupCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/user/AssignAddress", RequestNamespace="http://four51.com/services/user", ResponseNamespace="http://four51.com/services/user", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AssignAddress(string UserInteropID, AddressAssignment AddressAssignment, string SharedSecret) {
            this.Invoke("AssignAddress", new object[] {
                        UserInteropID,
                        AddressAssignment,
                        SharedSecret});
        }
        
        /// <remarks/>
        public void AssignAddressAsync(string UserInteropID, AddressAssignment AddressAssignment, string SharedSecret) {
            this.AssignAddressAsync(UserInteropID, AddressAssignment, SharedSecret, null);
        }
        
        /// <remarks/>
        public void AssignAddressAsync(string UserInteropID, AddressAssignment AddressAssignment, string SharedSecret, object userState) {
            if ((this.AssignAddressOperationCompleted == null)) {
                this.AssignAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssignAddressOperationCompleted);
            }
            this.InvokeAsync("AssignAddress", new object[] {
                        UserInteropID,
                        AddressAssignment,
                        SharedSecret}, this.AssignAddressOperationCompleted, userState);
        }
        
        private void OnAssignAddressOperationCompleted(object arg) {
            if ((this.AssignAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssignAddressCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/user/AssignCostCenter", RequestNamespace="http://four51.com/services/user", ResponseNamespace="http://four51.com/services/user", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AssignCostCenter(string UserInteropID, string CostCenterInteropID, string SharedSecret) {
            this.Invoke("AssignCostCenter", new object[] {
                        UserInteropID,
                        CostCenterInteropID,
                        SharedSecret});
        }
        
        /// <remarks/>
        public void AssignCostCenterAsync(string UserInteropID, string CostCenterInteropID, string SharedSecret) {
            this.AssignCostCenterAsync(UserInteropID, CostCenterInteropID, SharedSecret, null);
        }
        
        /// <remarks/>
        public void AssignCostCenterAsync(string UserInteropID, string CostCenterInteropID, string SharedSecret, object userState) {
            if ((this.AssignCostCenterOperationCompleted == null)) {
                this.AssignCostCenterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssignCostCenterOperationCompleted);
            }
            this.InvokeAsync("AssignCostCenter", new object[] {
                        UserInteropID,
                        CostCenterInteropID,
                        SharedSecret}, this.AssignCostCenterOperationCompleted, userState);
        }
        
        private void OnAssignCostCenterOperationCompleted(object arg) {
            if ((this.AssignCostCenterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssignCostCenterCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/user/Delete", RequestNamespace="http://four51.com/services/user", ResponseNamespace="http://four51.com/services/user", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] Delete(string[] UserInteropIDs, string SharedSecret) {
            object[] results = this.Invoke("Delete", new object[] {
                        UserInteropIDs,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string[] UserInteropIDs, string SharedSecret) {
            this.DeleteAsync(UserInteropIDs, SharedSecret, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string[] UserInteropIDs, string SharedSecret, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        UserInteropIDs,
                        SharedSecret}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/user")]
    public partial class UserAssociation {
        
        private string userInteropIDField;
        
        private string[] costCenterInteropIDsField;
        
        private string[] groupInteropIDsField;
        
        private AddressAssignment[] addressesField;
        
        private OrderFieldAssignment[] orderFieldsField;
        
        /// <remarks/>
        public string UserInteropID {
            get {
                return this.userInteropIDField;
            }
            set {
                this.userInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string[] CostCenterInteropIDs {
            get {
                return this.costCenterInteropIDsField;
            }
            set {
                this.costCenterInteropIDsField = value;
            }
        }
        
        /// <remarks/>
        public string[] GroupInteropIDs {
            get {
                return this.groupInteropIDsField;
            }
            set {
                this.groupInteropIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AddressAssignment[] Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public OrderFieldAssignment[] OrderFields {
            get {
                return this.orderFieldsField;
            }
            set {
                this.orderFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/user")]
    public partial class AddressAssignment {
        
        private string addressInteropIDField;
        
        private bool useForShippingField;
        
        private bool useForBillingField;
        
        /// <remarks/>
        public string AddressInteropID {
            get {
                return this.addressInteropIDField;
            }
            set {
                this.addressInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public bool UseForShipping {
            get {
                return this.useForShippingField;
            }
            set {
                this.useForShippingField = value;
            }
        }
        
        /// <remarks/>
        public bool UseForBilling {
            get {
                return this.useForBillingField;
            }
            set {
                this.useForBillingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/user")]
    public partial class UserProperties {
        
        private string userInteropIDField;
        
        private string companyInteropIDField;
        
        private string userNameField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string phoneNumberField;
        
        private string emailField;
        
        private string passwordField;
        
        private bool activeField;
        
        private bool termsAcceptedField;
        
        /// <remarks/>
        public string UserInteropID {
            get {
                return this.userInteropIDField;
            }
            set {
                this.userInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyInteropID {
            get {
                return this.companyInteropIDField;
            }
            set {
                this.companyInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public bool TermsAccepted {
            get {
                return this.termsAcceptedField;
            }
            set {
                this.termsAcceptedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/user")]
    public partial class ErrorReport {
        
        private string interopIDField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string InteropID {
            get {
                return this.interopIDField;
            }
            set {
                this.interopIDField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/user")]
    public partial class OrderFieldAssignment {
        
        private string nameField;
        
        private string[] optionInteropIDsField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string[] OptionInteropIDs {
            get {
                return this.optionInteropIDsField;
            }
            set {
                this.optionInteropIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SyncAssociationsCompletedEventHandler(object sender, SyncAssociationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncAssociationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncAssociationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SaveCompletedEventHandler(object sender, SaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AssignToGroupCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void RemoveFromGroupCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AssignAddressCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AssignCostCenterCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591