//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34011.
// 
#pragma warning disable 1591

namespace Four51.APISDK.Four51SpendingAccount {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SpendingAccountSoap", Namespace="http://four51.com/services/SpendingAccount")]
    public partial class SpendingAccount : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddToBalanceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SpendingAccount() {
            this.Url = global::Four51.APISDK.Properties.Settings.Default.Four51_APISDK_Four51SpendingAccount_SpendingAccount;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveCompletedEventHandler SaveCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event AddToBalanceCompletedEventHandler AddToBalanceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/SpendingAccount/Save", RequestNamespace="http://four51.com/services/SpendingAccount", ResponseNamespace="http://four51.com/services/SpendingAccount", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Save(string InteropID, string Name, string Label, string SpendingAccountTypeName, string CompanyInteropID, string UserInteropID, string GroupInteropID, decimal Balance, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> StartDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> ExpirationDate, string SharedSecret) {
            this.Invoke("Save", new object[] {
                        InteropID,
                        Name,
                        Label,
                        SpendingAccountTypeName,
                        CompanyInteropID,
                        UserInteropID,
                        GroupInteropID,
                        Balance,
                        StartDate,
                        ExpirationDate,
                        SharedSecret});
        }
        
        /// <remarks/>
        public void SaveAsync(string InteropID, string Name, string Label, string SpendingAccountTypeName, string CompanyInteropID, string UserInteropID, string GroupInteropID, decimal Balance, System.Nullable<System.DateTime> StartDate, System.Nullable<System.DateTime> ExpirationDate, string SharedSecret) {
            this.SaveAsync(InteropID, Name, Label, SpendingAccountTypeName, CompanyInteropID, UserInteropID, GroupInteropID, Balance, StartDate, ExpirationDate, SharedSecret, null);
        }
        
        /// <remarks/>
        public void SaveAsync(string InteropID, string Name, string Label, string SpendingAccountTypeName, string CompanyInteropID, string UserInteropID, string GroupInteropID, decimal Balance, System.Nullable<System.DateTime> StartDate, System.Nullable<System.DateTime> ExpirationDate, string SharedSecret, object userState) {
            if ((this.SaveOperationCompleted == null)) {
                this.SaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOperationCompleted);
            }
            this.InvokeAsync("Save", new object[] {
                        InteropID,
                        Name,
                        Label,
                        SpendingAccountTypeName,
                        CompanyInteropID,
                        UserInteropID,
                        GroupInteropID,
                        Balance,
                        StartDate,
                        ExpirationDate,
                        SharedSecret}, this.SaveOperationCompleted, userState);
        }
        
        private void OnSaveOperationCompleted(object arg) {
            if ((this.SaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/SpendingAccount/Delete", RequestNamespace="http://four51.com/services/SpendingAccount", ResponseNamespace="http://four51.com/services/SpendingAccount", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Delete(string InteropID, string SharedSecret) {
            this.Invoke("Delete", new object[] {
                        InteropID,
                        SharedSecret});
        }
        
        /// <remarks/>
        public void DeleteAsync(string InteropID, string SharedSecret) {
            this.DeleteAsync(InteropID, SharedSecret, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string InteropID, string SharedSecret, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        InteropID,
                        SharedSecret}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/SpendingAccount/AddToBalance", RequestNamespace="http://four51.com/services/SpendingAccount", ResponseNamespace="http://four51.com/services/SpendingAccount", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddToBalance(string InteropID, decimal Value, string SharedSecret) {
            this.Invoke("AddToBalance", new object[] {
                        InteropID,
                        Value,
                        SharedSecret});
        }
        
        /// <remarks/>
        public void AddToBalanceAsync(string InteropID, decimal Value, string SharedSecret) {
            this.AddToBalanceAsync(InteropID, Value, SharedSecret, null);
        }
        
        /// <remarks/>
        public void AddToBalanceAsync(string InteropID, decimal Value, string SharedSecret, object userState) {
            if ((this.AddToBalanceOperationCompleted == null)) {
                this.AddToBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddToBalanceOperationCompleted);
            }
            this.InvokeAsync("AddToBalance", new object[] {
                        InteropID,
                        Value,
                        SharedSecret}, this.AddToBalanceOperationCompleted, userState);
        }
        
        private void OnAddToBalanceOperationCompleted(object arg) {
            if ((this.AddToBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddToBalanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SaveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DeleteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AddToBalanceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591